version: '3'

services:

  mysql-development:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: neebal
      MYSQL_DATABASE: nodejs
    ports:
      - "3308:3306"
    volumes: 
      - ./data:/var/lib/mysql 
